- name: condition
  hosts: web
  become: yes
  tasks:
  - name: checking the condition
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "linux"
  - name: checking
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "ubantu"