- name: checking the number
  hosts: web
  vars:
    my_num: 10
  tasks:
  - name: checking the given number is greater
    ansible.builtin.debug:
      msg: "given number is > {{ my_num }}"
    when: my_num > 5
  - name: checking the given number
    ansible.builtin.debug:
      msg: "given number is lesst than {{ my_num }}"
    when: my_num <= 9