- name: functions
  hosts: local
  connection: local
  vars:
    fruits: "apple,banana,grape"
  tasks:
  - name: spliting funtion
    ansible.builtin.debug:
      msg: "{{ fruits | split (',') }}"
    register: fruits
  - name: register
    ansible.builtin.debug:
      msg: {{ fruits }}
    