- name: register
  hosts: local
  connection: yes
  tasks:
  - name: storing the values in register keys
    anisble.builtin.command: ls -ltr
      register: command_result
  - name: regsiter
    ansible.builtin.debug:
      msg: {{ command_result }}