- name: register
  hosts: local
  connection: local
  tasks:
  - name: storing the values in register keys
    anisble.builtin.command: ls -ltr
      register: command_result
  - name: regsiter
    ansible.builtin.debug:
      msg: "{{ command_result.stdout_lines }}"